# Generated by Django 4.0.2 on 2022-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('birth', models.DateField(verbose_name='data de nascimento')),
                ('sex', models.CharField(max_length=1, verbose_name='sexo')),
                ('adress', models.CharField(max_length=250, verbose_name='endereço')),
                ('mail', models.CharField(max_length=255, verbose_name='e-mail')),
                ('sumary', models.TextField(verbose_name='sobre')),
                ('photo', models.ImageField(upload_to=None, verbose_name='foto')),
                ('personalSite', models.URLField(verbose_name='site pessoal')),
            ],
            options={
                'verbose_name': 'Dados Pessoais',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
    ]
