# Generated by Django 4.0.2 on 2022-02-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redessociais_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociais',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='pessoa'),
            preserve_default=False,
        ),
    ]
