# Generated by Django 4.0.2 on 2022-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dadospessoais_adress_alter_dadospessoais_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foto', verbose_name='foto'),
        ),
    ]
