# Generated by Django 4.0.2 on 2022-02-25 18:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dadospessoais_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
