# Generated by Django 4.0.2 on 2022-02-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_dadospessoais_adress_alter_dadospessoais_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('level', models.PositiveSmallIntegerField(verbose_name='nível')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'habilidade',
                'verbose_name_plural': 'habilidades',
            },
        ),
    ]
