# Generated by Django 4.0.2 on 2022-02-25 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='nível'),
        ),
    ]
