# Generated by Django 4.0.2 on 2022-02-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dadospessoais_adress_alter_dadospessoais_birth_and_more'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='pessoa'),
            preserve_default=False,
        ),
    ]
