# Generated by Django 4.0.2 on 2022-02-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_dadospessoais_adress_alter_dadospessoais_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=200, verbose_name='empresa')),
                ('current', models.BooleanField(default=False, verbose_name='atual')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('role', models.CharField(max_length=150, verbose_name='cargo')),
                ('description', models.TextField(verbose_name='descrição das atribuições')),
                ('city', models.CharField(max_length=150, verbose_name='município')),
                ('country', models.CharField(max_length=150, verbose_name='país')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadospessoais', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
            },
        ),
    ]
